require "user.plugins"
require "user.options"
require "user.keymaps"
require "user.lualine"
require "user.comment"
require "user.indentline"
require "user.gitsigns"
require "user.telescope"
require "user.treesitter"
require "user.lsp"
require "user.neodev"
require "user.fidget"
require "user.colorscheme"
require "user.autopairs"
require "user.nvim-tree"
require "user.bufferline"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
require "user.mini"
--[[ require "user.transparent" ]]
require "user.cutlass"
require "user.spectre"
require "user.treesitter-context"

vim.wo.colorcolumn='80'
